<!DOCTYPE html>

<%@include file="/apps/mcd/global/global.jsp"%>
   

<%@ page import="java.util.ArrayList,
         java.util.Iterator,
         java.util.Date,
         com.day.cq.wcm.api.PageFilter,
         javax.jcr.Binary,javax.jcr.Node,javax.jcr.Session,org.apache.sling.jcr.api.SlingRepository,
         org.apache.sling.api.scripting.SlingScriptHelper,org.apache.sling.api.wrappers.SlingRequestPaths,
         com.day.cq.security.User,com.day.cq.security.Group,java.text.*
       "%> 
       
<html>
       
<meta http-equiv="Content-Type" content="text/html; utf-8">

<cq:includeClientLib categories="cq.wcm.edit" />
<script type="text/javascript" src="/scripts/jquery-1.3.2.min.js"></script>    

<link rel="stylesheet" type="text/css" href="/css/ext-all.css" />
 
<title>ACE Set Off Time Utility</title>

<script type="text/javascript" src="/scripts/sling.js"></script>
<style type="text/css">

#CQ .button {  
    background:#DFDFDF;
    -webkit-box-shadow:inset 0px -1px 5px -18px #ffffff;
    box-shadow:inset 0px -1px 5px -18px #ffffff;
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
    background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
    background-color:#ededed;
    border-radius:11px;
    border:1px solid #aaaaaa;
    display:inline-block;
    color:#777777;
    font-family:arial;
    font-size:11px;
    font-weight:bold;
    padding:3px 27px;
    text-decoration:none;
    text-shadow:-46px 1px 50px #ffffff
    cursor:pointer;
}.button:hover {
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
    background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
    background-color:#dfdfdf;
}.button:active {
    position:relative;
    top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
  <style>
    .cpathclass{
    align:right;
    width:400px;
    }
    
    .x-form-trigger {
    background:url("/content/dam/accessmcd/awesome_bar/corp/searchsite.jpg") no-repeat scroll center center lightgrey;
    border: 1px solid #B5B8C8;
    cursor: pointer;
    float: right;
    height: 17px;
    width: 18px;
    *margin-top:-19px;margin-top:-19px\9;

}
.x-form-item {
    display: block;
    margin-bottom: 15px;
    position: relative;
}
     .x-fit-item{
    
    
     //background: none repeat scroll 0 0 white;
    border-color: #C5C5C5 #99BBE8 #99BBE8;
    border-right: 1px solid #99BBE8;
    border-style: solid;
    border-width: 1px;
    height: 290px;
    overflow-y: auto;
    }

.x-panel-header {
    background: -moz-linear-gradient(center top , #DAE7F6, #CDDEF3 45%, #ABC7EC 46%, #ABC7EC 50%, #B8CFEE 51%, #CBDDF3) repeat scroll 0 0 #CBDDF3;
    border: 1px solid #99BBE8;
    color: #04468C;
    font-size: 10px;
    font-weight: bold;
    padding: 5px 4px 4px 5px;
}

.x-panel-body
 {
    background: none repeat scroll 0 0 white;
    border: 1px solid #99BBE8;
    color: black;
    height: 70px;
}
 .x-btn-mc{
    background-color: lightgrey;
    border-style: solid;
    border-width: 1px;
    padding: 2px; 
    margin:3px;
    font-size:12px;
    border-color:black;
    }
    .x-btn button {
    background: lightgrey;
    border: 0 none;
    margin: 0;
    outline: 0 none;
    overflow: hidden;
    padding: 0;
    vertical-align: bottom;
    width: auto;
    font-size:12px;
}

    fieldset { 
        border: 1px solid #B5B8C8;
        display: block;
        margin-bottom: 10px;
        padding: 10px; 
   }

legend {
    color: #15428B;
    font: 11px/16px bold tahoma,arial,verdana,sans-serif;
    padding: 0 3px;
  }
#CQ .reportlabel{
    margin-left:120px;
    font-size:12px;
    color:#15428B;
    font-weight:bold;
}
#CQ html, #CQ body, #CQ fieldset, #CQ input, #CQ p, #CQ blockquote, #CQ th, #CQ td {
    margin: auto;
    padding-left: 10px;
    padding-top:5px;
}
#CQ .x-panel-header-text{
    margin-left:0px;
}
#CQ .x-tree-node a span, #CQ .x-dd-drag-ghost a span {
    margin-left:0px;
    font-size:11px;
    font-weight:normal;
}
 </style>
  
</head>

   
<%
final User user = slingRequest.getResourceResolver().adaptTo(User.class); //instantiate User object

%>

<body style="background-color:#FFFDDF" id="CQ">
<table border=0 height="100%" width="100%" >
  <tr>
  <td width="100%" valign="top">
            <table border=0 width="100%" height="100%">
                <tr>
                    <td valign="top" width="100%">
                         <form name="auth1form" id="auth1form" >
                            <div style="color:red;font-size:12px;text-align:right;margin-top:0px\9; ">Logged In User:&nbsp;<span style="color:red;font-size:13px;font-weight:bold;margin-left:0px;"><%=user.getName()%></span></div>
                           <div id="page"></div>
                         </form>
                    </td>  
                </tr>
                <tr>
                 <td align="top" valign="top"> 
                   <div id="pages" style="margin-top:15px;"></div>  
                </td>
               </tr>
            </table>
              
    </td>
    </tr>
</table>  



<script>
     
   // Page Report Section
 
        var author1 =  new CQ.Ext.form.FormPanel({
            frame:false,
            renderTo: 'CQ',
            id:"pageinfo",
            bodyStyle:'padding:15px',
            width: '64%',
            height:140,
            style:'margin-left:205px;',
            fieldDefaults: {
                msgTarget: 'side',
                labelWidth: 300
            },
            defaultType: 'textfield',
            items:[
                { 
                    xtype:'browsefield',        
                    id:'ppath',
                    name:'ppath',
                    fieldClass:'cpathclass',
                    fieldLabel:'Enter Page Path',
                    maxLength:120,
                    width:'200px',
                    labelSeparator:':',
                    rootPath:'/content',
                    hideTrigger:false
                },
                { 
                    xtype:'numberfield',        
                    id:'offtime',
                    name:'offtime',
                    fieldLabel:'New Off Time(in months)',
                    labelSeparator:':'
                },
                { 
                    xtype:'button',        
                    id:'offbutton',
                    name:'offbutton',
                    text : 'Set Off Time',
                    labelSeparator:':',
                    handler : getPage
                }
            ],
            title: 'ACE Set New Off Time'
            
        });


  
        
 var loading="<div id='loadingajax' style='margin-left:550px;margin-top:20px;'><img src='/images/ajax-loader.gif'></div>";
 
 
    function setComponentPath(combo) 
    {
     $("#compPath").val(combo.value);
    }
 
    
      
    // function to fetch the results
    

    function getPage(user,action)
    {     
      var path=document.getElementById("ppath").value;
      var time =document.getElementById("offtime").value;
      if(jQuery.trim(path) == '' || jQuery.trim(time) == '')
              {
               alert("Please enter page path/Time");
              
              }
     else
     {     
            $('#newpageid').after(loading);           
             var data=Sling.httpGet("<%=currentPage.getPath()%>.ace.request.html?path="+escape(path)+"&time="+escape(time)); 
            
            var text=data.responseText;  
             $('#grid-table').hide();
                if(text.indexOf("norecordfound")<0){
                   $('#grid-table').html(data.responseText);
                  }
                else{
                $('#grid-table').html("No Record Found");
               // return;
               } 
                 $('#resultdiv').remove();   
                var resultHTML = "<div id='resultdiv' style='margin-left:205px;margin-top:10px;width:800px;'>" + $('#grid-table').html() + "</div>";
                $('#newpageid').after(resultHTML);    
                $('#loadingajax').remove();
                 $('#resultdiv').show();  
                $('#grid-table').show();
          
           
        }
        
        
       
        
    }


   
    </script>
   <div id="grid-table" style="width:100%;height:100%"></div>  
   </body>
</html>

         